# Worksheet 04

Name: Kenise Neal

UID: U55010739

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

p is the parameter and d is the dimension of the space

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Euclidean distance is the shortest path between the start and end which results in a straight line between the two. Manhattan distance is the sum of all absolute distances between all between corresponding coordinates of two points.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

The larger p gets, the closer d(A,B) gets to 0 (but never touches 0).

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No, because it is not a it violates the triangle inequality, therefore when p < 1, it is not a metric.

e) when would you use cosine similarity over the euclidan distance?

When direction matters more than magnitude.

f) what does the jaccard distance account for that the manhattan distance doesn't?

Jaccard Distance accounts for the size of the intersection of two sets.

#### Part 2

Consider the following two sentences:

In [21]:
import numpy as np

s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [9]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [10]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'is', 'name', 'Bob', 'Alice', 'my']
[1, 1, 1, 0, 1, 1]


Let's add a new sentence to our corpus:

In [11]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [12]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['Claude', 'hello', 'is', 'name', 'Bob', 'Alice', 'hi', 'my']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [13]:
v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
print(v1)
print(v2)
print(v3)

[0, 1, 1, 1, 0, 1, 0, 1]
[0, 1, 1, 1, 1, 0, 0, 1]
[1, 0, 1, 1, 0, 0, 1, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [14]:
def minkowski_dist(x,y,p):
    sum = 0
    for a,b in zip(x,y):
        sum = (abs(a - b)**p) + sum
    return (sum**(1/p))

def manhattan_dist(x,y):
    return minkowski_dist(x,y,1)

In [15]:
print(manhattan_dist(v1,v2))
print(manhattan_dist(v2,v3))
print(manhattan_dist(v3,v1))
print("")
print("The two vectors that are the most similar under the manhattan distance function is vector 1 and vector 2.")

2.0
4.0
4.0

The two vectors that are the most similar under the manhattan distance function is vector 1 and vector 2.


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [29]:
corpus = [ "hi Alice", "hello Claude", "Bob my name is Claude", "hi Claude my name is Alice", "hello Bob"]

all_words_2 = list(set([item for x in corpus for item in x.split()]))

v4 = [1 if x in corpus[0] else 0 for x in all_words_2]
v5 = [1 if x in corpus[1] else 0 for x in all_words_2]
v6 = [1 if x in corpus[2] else 0 for x in all_words_2]
v7 = [1 if x in corpus[3] else 0 for x in all_words_2]
v8 = [1 if x in corpus[4] else 0 for x in all_words_2]

matrix = np.mat([v4, v5, v6,v7,v8])
print(matrix)

[[0 0 0 0 0 1 1 0]
 [1 1 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 1]
 [1 0 1 1 0 1 1 1]
 [0 1 0 0 1 0 0 0]]


e) How many rows and columns does this matrix have?

In [33]:
dim = np.shape(matrix)
rows, cols = dim

# We have 5 rows and 8 cols

print("Rows:", rows)
print("Cols:", cols)

Rows: 5
Cols: 8


f) When using the Manhattan distance, which two sentences are the most similar?

In [34]:
# Comparing v4 to all other v's
print("Comparing v4 to v5:", manhattan_dist(v4,v5))
print("Comparing v4 to v6:", manhattan_dist(v4,v6))
print("Comparing v4 to v7:", manhattan_dist(v4,v7))
print("Comparing v4 to v8:", manhattan_dist(v4,v8))

# Comparing v5 to all other v's
print("Comparing v5 to v4:", manhattan_dist(v5,v4))
print("Comparing v5 to v6:", manhattan_dist(v5,v6))
print("Comparing v5 to v7:", manhattan_dist(v5,v7))
print("Comparing v5 to v8:", manhattan_dist(v5,v8))

# Comparing v6 to all other v's
print("Comparing v6 to v5:", manhattan_dist(v6,v5))
print("Comparing v6 to v4:", manhattan_dist(v4,v6))
print("Comparing v6 to v7:", manhattan_dist(v6,v7))
print("Comparing v6 to v8:", manhattan_dist(v6,v8))

# Comparing v7 to all other v's
print("Comparing v7 to v5:", manhattan_dist(v7,v5))
print("Comparing v7 to v6:", manhattan_dist(v7,v6))
print("Comparing v7 to v4:", manhattan_dist(v4,v7))
print("Comparing v7 to v8:", manhattan_dist(v7,v8))

# Comparing v8 to all other v's
print("Comparing v8 to v5:", manhattan_dist(v8,v5))
print("Comparing v8 to v6:", manhattan_dist(v8,v6))
print("Comparing v8 to v7:", manhattan_dist(v8,v7))
print("Comparing v8 to v4:", manhattan_dist(v4,v8))


Comparing v4 to v5: 4.0
Comparing v4 to v6: 7.0
Comparing v4 to v7: 4.0
Comparing v4 to v8: 4.0
Comparing v5 to v4: 4.0
Comparing v5 to v6: 5.0
Comparing v5 to v7: 6.0
Comparing v5 to v8: 2.0
Comparing v6 to v5: 5.0
Comparing v6 to v4: 7.0
Comparing v6 to v7: 3.0
Comparing v6 to v8: 5.0
Comparing v7 to v5: 6.0
Comparing v7 to v6: 3.0
Comparing v7 to v4: 4.0
Comparing v7 to v8: 8.0
Comparing v8 to v5: 2.0
Comparing v8 to v6: 5.0
Comparing v8 to v7: 8.0
Comparing v8 to v4: 4.0


According to the comparasions above, v5 and v8 are the most similar. "Hello Claude" and "Hello Bob"